POST http://localhost:8080/user
content-type: application/json

{
    "first_name": "rose",
    "last_name": "towne",
    "email_address": "h4@gmail.com",
    "phone_number": "4633753853",
    "street_address": "634858 W 23 S",
    "city": "Glendale",
    "state": "Arizona",
    "zipcode": "85306"
}